### ISSUE TITLE
Email Verification Not Working

### ISSUE THREAD

**Issue by the-can-of-soup** [PenguinMod/PenguinMod-Home#358]
I went to link my email address to my PenguinMod account, and I received the verification email, but upon clicking the link I get the following JSON response:
```JSON
{"error":"InvalidState. Your link has most likely expired, please try again."}
```
I clicked the link within 5 minutes of selecting my email address in settings, but now in PenguinMod I just have this banner:
> Check your email to verify your email address, or check settings to resend the email. 

There is no option in settings to resend the email, and the "Verify my email" button does nothing now. I even tried setting my email again, but it said the email is already in use.

**Comment by Steve0Greatness** [comment]
Should be fixed, now.

**Comment by nikolaspaiva07** [comment]
my penguin username is trickyowl350 and my account is still not verified. still no verification link.

**Comment by the-can-of-soup** [comment]
> Should be fixed, now.

Not when you said that, but this commit should've fixed it now:

https://github.com/PenguinMod/PenguinMod-BackendApi/commit/a67665f701bb0658216231bf06b49d19621ced9b

**Comment by the-can-of-soup** [comment]
> my penguin username is trickyowl350 and my account is still not verified. still no verification link.

Consider opening a separate issue, because this issue was about the link not being formatted correctly, and it seems yours is about it not being sent in the first place.

**Comment by CodingOfScratch** [comment]
soooo what is the solution i have same issue

**Comment by the-can-of-soup** [comment]
> soooo what is the solution i have same issue

I said it was fixed.

The email address was not URL encoded when the verification URL was created, so it became a malformed URL. The workaround was to manually URL encode the email address and put that into the verification URL, then go to it.

However, as I already said, it should be fixed now by this commit: https://github.com/PenguinMod/PenguinMod-BackendApi/commit/a67665f701bb0658216231bf06b49d19621ced9b

So unless that commit did not fix it, you are likely experiencing a different issue.

**Comment by richvpjr** [comment]
i think i might be having the same problem
my username is SuperSMG5 and i keep trying to send the email, but its not working.
yes, i set it to my email, yes, i checked all outlook inboxes including junk, yes i refreshed the page several times but nothing changed.
can you help?

**Comment by the-can-of-soup** [comment]
> i think i might be having the same problem my username is SuperSMG5 and i keep trying to send the email, but its not working. yes, i set it to my email, yes, i checked all outlook inboxes including junk, yes i refreshed the page several times but nothing changed. can you help?

Why does everyone keep commenting on this fixed issue about unrelated problems?? Make a new issue unless it is the same problem reappearing for some reason.
